In [65]:
import pandas as pd
import numpy as np
from collections import defaultdict

In [6]:
path = '../data/Datasus/csv'

### Animais Peçonhentos

In [70]:
df = pd.read_csv(f'{path}/ANIMBR07.csv', encoding='ISO-8859-1')

df.columns

Index(['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC',
       'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF',
       'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N',
       'ANT_DT_ACI', 'ANT_UF', 'ANT_MUNIC_', 'ANT_LOCALI', 'ANT_TEMPO_',
       'ANT_LOCA_1', 'MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO',
       'CLI_NECROS', 'CLI_LOCAL_', 'CLI_LOCA_1', 'MCLI_SIST', 'CLI_NEURO',
       'CLI_HEMORR', 'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL', 'CLI_OUTR_2',
       'CLI_OUTR_3', 'CLI_TEMPO_', 'TP_ACIDENT', 'ANI_TIPO_1', 'ANI_SERPEN',
       'ANI_ARANHA', 'ANI_LAGART', 'TRA_CLASSI', 'CON_SOROTE', 'NU_AMPOLAS',
       'NU_AMPOL_1', 'NU_AMPOL_8', 'NU_AMPOL_6', 'NU_AMPOL_4', 'NU_AMPO_7',
       'NU_AMPO_5', 'NU_AMPOL_9', 'NU_AMPOL_3', 'COM_LOC', 'COM_SECUND',
       'COM_NECROS', 'COM_COMPOR', 'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM',
       'COM_RENAL', 

In [95]:
columns_to_keep = ['DT_NOTIFIC', 'SG_UF_NOT']
df = df[columns_to_keep]
df = df.query('SG_UF_NOT != 0')
df

DT_NOTIFIC  SG_UF_NOT
0       2007-01-18         29
1       2007-01-17         29
2       2007-01-19         29
3       2007-01-09         29
4       2007-01-01         29
...            ...        ...
103368  2007-12-01         35
103369  2007-12-23         35
103370  2007-12-13         15
103371  2007-12-05         41
103372  2007-12-22         50

[103373 rows x 2 columns]

In [98]:
uf_dict = {
    11: 'RO',	
    12: 'AC',	
    13: 'AM',	
    14: 'RR',	
    15: 'PA',	
    16: 'AP',	
    17: 'TO',	
    21: 'MA',	
    22: 'PI',	
    23: 'CE',	
    24: 'RN',	
    25: 'PB',	
    26: 'PE',	
    27: 'AL',	
    28: 'SE',	
    29: 'BA',	
    31: 'MG',	
    32: 'ES',	
    33: 'RJ',	
    35: 'SP',	
    41: 'PR',	
    42: 'SC',	
    43: 'RS',	
    50: 'MS',	
    51: 'MT',	
    52: 'GO',	
    53: 'DF'
}

primary_dict = defaultdict(lambda: ['Year', 'State', np.zeros(12, dtype=int)])

for row in df.to_dict(orient='records'):
    date = row['DT_NOTIFIC'].split('-')
    index = date[0] + '-' + uf_dict[row['SG_UF_NOT']]
    primary_dict[index][0] = int(date[0])
    primary_dict[index][1] = uf_dict[row['SG_UF_NOT']]
    primary_dict[index][2][int(date[1]) - 1] += 1

In [99]:
primary_dict

defaultdict(<function __main__.<lambda>()>,
            {'2007-BA': [2007,
              'BA',
              array([916, 686, 916, 878, 908, 699, 720, 632, 698, 830, 825, 849])],
             '2007-SC': [2007,
              'SC',
              array([ 933,  886, 1071,  730,  409,  345,  222,  311,  551,  670,  739,
                      844])],
             '2007-TO': [2007,
              'TO',
              array([ 89,  74,  97,  77, 152, 125,  97,  76,  82, 105, 126, 118])],
             '2007-PR': [2007,
              'PR',
              array([1779, 1894, 2295, 1614,  944,  721,  533,  704,  978, 1321, 1333,
                     1494])],
             '2007-MG': [2007,
              'MG',
              array([1567, 1482, 1795, 1529, 1271, 1001, 1020, 1189, 1143, 1247, 1377,
                     1406])],
             '2007-GO': [2007,
              'GO',
              array([206, 185, 224, 193, 116, 107, 119,  78, 110, 135, 151, 184])],
             '2007-SP': [2007,
              'S

In [55]:
a = {}
a['1999 - RJ'] = [['1999']['RJ'][ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]]

df2 = pd.DataFrame.from_dict(a, orient='index', columns=['Year', 'State', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

Year State                                Months
1999 - RJ  1999    RJ  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]